use crate::protocol::{ToolHandler, ToolInputSchema, ToolProperty};
use async_trait::async_trait;
use serde_json::Value;

#[derive(Clone)]
struct Slide {
    number: usize,
    title: String,
    slide_type: String,
    duration_secs: u32,
    key_points: Vec<String>,
    visual_suggestion: String,
    notes: String,
}

fn talk_type_config(talk_type: &str) -> (usize, usize, &str) {
    match talk_type {
        "conference" => (15, 18, "Conference Talk (15 min)"),
        "seminar" => (45, 25, "Academic Seminar (45 min)"),
        "defense" => (60, 30, "Thesis Defense (60 min)"),
        "grant" => (15, 18, "Grant Pitch (15 min)"),
        "journal_club" => (30, 20, "Journal Club (30 min)"),
        "teaching" => (50, 30, "Teaching Tutorial (50 min)"),
        _ => (15, 18, "Conference Talk (15 min)"),
    }
}

fn build_slide_markdown(
    topic: &str,
    talk_type: &str,
    slides: &[Slide],
    include_speaker_notes: bool,
) -> String {
    let mut md = String::new();
    let (duration_min, _, config_name) = talk_type_config(talk_type);
    let today = chrono::Local::now().format("%Y-%m-%d").to_string();

    md.push_str("# Slide Deck: ");
    md.push_str(topic);
    md.push_str("\n\n");
    md.push_str(&format!("**Type:** {} | ", config_name));
    md.push_str(&format!("**Duration:** ~{} minutes | ", duration_min));
    md.push_str(&format!("**Slides:** {} | **Date:** {}\n\n", slides.len(), today));
    md.push_str("---\n\n");

    md.push_str("## Presentation Plan\n\n");
    md.push_str(&format!("This deck covers **{}** in {} format with {} slides.\n\n",
        topic, config_name, slides.len()));

    md.push_str("### Slide Sequence\n\n");
    md.push_str("| # | Slide Title | Type | Duration | Visual |\n");
    md.push_str("|---|------------|------|---------|--------|\n");
    for slide in slides {
        md.push_str(&format!("| {} | {} | {} | {}s | {} |\n",
            slide.number, slide.title, slide.slide_type,
            slide.duration_secs, slide.visual_suggestion));
    }
    md.push_str("\n---\n\n");

    for slide in slides {
        md.push_str("## ");
        md.push_str(&slide.number.to_string());
        md.push_str(". ");
        md.push_str(&slide.title);
        md.push_str("\n\n");

        md.push_str(&format!("**Type:** {} | **Time:** {}s\n\n", slide.slide_type, slide.duration_secs));

        md.push_str("**Key Points:**\n");
        for point in &slide.key_points {
            md.push_str(&format!("- {}\n", point));
        }
        md.push('\n');

        md.push_str(&format!("**Visual Suggestion:** {}\n\n", slide.visual_suggestion));

        if include_speaker_notes && !slide.notes.is_empty() {
            md.push_str("**Speaker Notes:**\n");
            md.push_str(&slide.notes);
            md.push_str("\n\n");
        }

        md.push_str("---\n\n");
    }

    md.push_str("## Presentation Tips\n\n");
    md.push_str("1. **Timing:** Aim for ~1 slide per minute; adjust based on audience engagement\n");
    md.push_str("2. **Visuals:** Each slide should have a strong visual element (figure, diagram, or icon)\n");
    md.push_str("3. **Citations:** Include 3-5 key references in your talk to establish credibility\n");
    md.push_str("4. **Story arc:** Follow hook → context → problem → approach → results → implications\n");
    md.push_str("5. **Practice:** Run through at least 3 times before presenting\n\n");

    md.push_str(&format!("_Generated by Rairos on {} for \"{}\"_\n", today, topic));

    md
}

pub struct PaperSlidesHandler;

#[async_trait]
impl ToolHandler for PaperSlidesHandler {
    fn name(&self) -> &str { "paper_slides_generate" }
    fn description(&self) -> &str { "Generate a structured slide deck outline for a research presentation with slide titles, key points, visual suggestions, timing, and speaker notes. Supports conference talks, seminars, thesis defenses, grant pitches, and journal clubs." }
    fn input_schema(&self) -> ToolInputSchema {
        ToolInputSchema::object(
            vec![
                ("topic".into(), ToolProperty::string("Research topic or paper title")),
                ("talk_type".into(), ToolProperty::string("Presentation type: conference (15min), seminar (45min), defense (60min), grant (15min), journal_club (30min), teaching (50min)")),
                ("include_notes".into(), ToolProperty::string("Include speaker notes: 'true' or 'false' (default: false)")),
                ("focus_slides".into(), ToolProperty::string("Focus areas as comma-separated: 'introduction,methods,results,discussion' (default: all)")),
            ].into_iter().collect(),
            vec!["topic".into()],
        )
    }
    async fn call(&self, params: Value) -> Result<Value, String> {
        let topic = params["topic"].as_str().ok_or("Missing topic")?;
        let talk_type = params.get("talk_type").and_then(|v| v.as_str()).unwrap_or("conference");
        let include_notes = params.get("include_notes").and_then(|v| v.as_str()).unwrap_or("false") == "true";
        let focus_str = params.get("focus_slides").and_then(|v| v.as_str()).unwrap_or("");

        let (_duration_min, _slide_count, config_name) = talk_type_config(talk_type);
        let focus: Vec<&str> = if focus_str.is_empty() {
            vec!["introduction", "background", "methods", "results", "discussion", "conclusion"]
        } else {
            focus_str.split(',').map(|s| s.trim()).collect()
        };

        let mut slides = Vec::new();
        let mut slide_num = 1usize;

        slides.push(Slide {
            number: slide_num,
            title: topic.to_string(),
            slide_type: "Title".to_string(),
            duration_secs: 30,
            key_points: vec![
                format!("Topic: {}", topic),
                "Presenter: [Your Name]".to_string(),
                "Affiliation: [Institution]".to_string(),
                format!("{}", config_name),
            ],
            visual_suggestion: "Abstract background image or relevant scientific imagery".to_string(),
            notes: "Introduce yourself briefly. Set up the talk context. Establish why this topic matters right now.".to_string(),
        });
        slide_num += 1;

        slides.push(Slide {
            number: slide_num,
            title: "Why This Research Matters".to_string(),
            slide_type: "Hook".to_string(),
            duration_secs: 60,
            key_points: vec![
                "Current state of the field".to_string(),
                "Unmet need or knowledge gap".to_string(),
                "Potential impact of solving this".to_string(),
            ],
            visual_suggestion: "Icon collage or striking statistic visualization".to_string(),
            notes: "Grab attention immediately. State the problem clearly. Make the audience care.".to_string(),
        });
        slide_num += 1;

        if focus.contains(&"introduction") || focus.contains(&"background") {
            if talk_type != "conference" {
                slides.push(Slide {
                    number: slide_num,
                    title: "Background & Prior Work".to_string(),
                    slide_type: "Content".to_string(),
                    duration_secs: if talk_type == "seminar" || talk_type == "defense" { 180 } else { 90 },
                    key_points: vec![
                        "Key prior studies in this area".to_string(),
                        "Established methods and approaches".to_string(),
                        "What the community already knows".to_string(),
                    ],
                    visual_suggestion: "Timeline diagram or citation network visualization".to_string(),
                    notes: "Provide sufficient context. Cite 3-5 key papers. Show how your work builds on existing knowledge.".to_string(),
                });
                slide_num += 1;
            }

            slides.push(Slide {
                number: slide_num,
                title: "The Knowledge Gap".to_string(),
                slide_type: "Content".to_string(),
                duration_secs: if talk_type == "conference" { 60 } else { 120 },
                key_points: vec![
                    "What remains unknown or unsolved".to_string(),
                    "Limitations of existing approaches".to_string(),
                    "Open questions your research addresses".to_string(),
                ],
                visual_suggestion: "Gap visualization showing covered vs. uncovered territory".to_string(),
                notes: "Clearly articulate the gap. This motivates your entire study.".to_string(),
            });
            slide_num += 1;
        }

        slides.push(Slide {
            number: slide_num,
            title: "Research Questions & Objectives".to_string(),
            slide_type: "Content".to_string(),
            duration_secs: 60,
            key_points: vec![
                "Primary research question(s)".to_string(),
                "Specific objectives or hypotheses".to_string(),
                "Scope and boundaries of the study".to_string(),
            ],
            visual_suggestion: "Research question tree or objective hierarchy diagram".to_string(),
            notes: "State questions clearly and specifically. Make them answerable with your approach.".to_string(),
        });
        slide_num += 1;

        if focus.contains(&"methods") {
            slides.push(Slide {
                number: slide_num,
                title: "Methods".to_string(),
                slide_type: "Content".to_string(),
                duration_secs: if talk_type == "conference" { 120 } else { 300 },
                key_points: vec![
                    "Study design or approach".to_string(),
                    "Data collection or experimental setup".to_string(),
                    "Analysis methods and tools used".to_string(),
                ],
                visual_suggestion: "Flowchart showing methodology pipeline or experimental design diagram".to_string(),
                notes: "Be thorough enough for reproducibility in longer talks. Keep it high-level for conferences.".to_string(),
            });
            slide_num += 1;

            if talk_type == "seminar" || talk_type == "defense" {
                slides.push(Slide {
                    number: slide_num,
                    title: "Methodology Details".to_string(),
                    slide_type: "Content".to_string(),
                    duration_secs: 180,
                    key_points: vec![
                        "Detailed procedures and protocols".to_string(),
                        "Equipment and materials".to_string(),
                        "Quality control and validation steps".to_string(),
                    ],
                    visual_suggestion: "Detailed schematic or step-by-step workflow diagram".to_string(),
                    notes: "Go deep on methodology. Defenses require thorough method explanation.".to_string(),
                });
                slide_num += 1;
            }
        }

        if focus.contains(&"results") {
            let result_slides = match talk_type {
                "conference" => 2,
                "seminar" => 4,
                "defense" => 5,
                "grant" => 3,
                "journal_club" => 3,
                "teaching" => 3,
                _ => 3,
            };

            for i in 0..result_slides {
                slides.push(Slide {
                    number: slide_num,
                    title: format!("Results: Key Finding {}", i + 1),
                    slide_type: "Results".to_string(),
                    duration_secs: if talk_type == "conference" { 150 } else { 180 },
                    key_points: vec![
                        format!("Primary finding {}: [main result]", i + 1),
                        "Supporting evidence or statistics".to_string(),
                        "How this relates to your question".to_string(),
                    ],
                    visual_suggestion: format!("Figure {} or chart showing the key finding", i + 1),
                    notes: "Present results objectively. Show data with large, clear visualizations. Let the data speak.".to_string(),
                });
                slide_num += 1;
            }
        }

        if focus.contains(&"discussion") {
            slides.push(Slide {
                number: slide_num,
                title: "Discussion & Interpretation".to_string(),
                slide_type: "Content".to_string(),
                duration_secs: if talk_type == "conference" { 90 } else { 180 },
                key_points: vec![
                    "What your results mean".to_string(),
                    "How findings compare to prior work".to_string(),
                    "Novel contributions of this research".to_string(),
                ],
                visual_suggestion: "Comparison chart showing your results vs. prior literature".to_string(),
                notes: "Interpret don't overinterpret. Compare with 2-3 key papers from your intro.".to_string(),
            });
            slide_num += 1;

            slides.push(Slide {
                number: slide_num,
                title: "Limitations & Future Directions".to_string(),
                slide_type: "Content".to_string(),
                duration_secs: 90,
                key_points: vec![
                    "Key limitations of the study".to_string(),
                    "Alternative explanations considered".to_string(),
                    "Recommended future research directions".to_string(),
                ],
                visual_suggestion: "Forward-looking roadmap or opportunity map".to_string(),
                notes: "Be honest about limitations. Show self-awareness and scientific integrity.".to_string(),
            });
            slide_num += 1;
        }

        if focus.contains(&"conclusion") || focus.contains(&"conclusions") {
            slides.push(Slide {
                number: slide_num,
                title: "Conclusions".to_string(),
                slide_type: "Summary".to_string(),
                duration_secs: 60,
                key_points: vec![
                    "3 main takeaways from this work".to_string(),
                    "Broader implications for the field".to_string(),
                    "Actionable recommendations if applicable".to_string(),
                ],
                visual_suggestion: "Three key takeaway icons or summary graphic".to_string(),
                notes: "Wrap up with clear, memorable conclusions. Don't introduce new information.".to_string(),
            });
            slide_num += 1;
        }

        slides.push(Slide {
            number: slide_num,
            title: "Acknowledgments".to_string(),
            slide_type: "Closing".to_string(),
            duration_secs: 30,
            key_points: vec![
                "Funding sources and support".to_string(),
                "Collaborators and contributors".to_string(),
                "Data and resource providers".to_string(),
            ],
            visual_suggestion: "Logos of funding agencies or institution branding".to_string(),
            notes: "Be grateful and professional. Acknowledge all support received.".to_string(),
        });
        slide_num += 1;

        if talk_type == "seminar" || talk_type == "defense" {
            slides.push(Slide {
                number: slide_num,
                title: "References".to_string(),
                slide_type: "Closing".to_string(),
                duration_secs: 30,
                key_points: vec![
                    "Key citations (Author, Year)".to_string(),
                    "[Full reference list in handout]".to_string(),
                ],
                visual_suggestion: "Reference list with QR code to full bibliography".to_string(),
                notes: "List 5-10 most critical references. Provide full list as handout.".to_string(),
            });
            slide_num += 1;
        }

        slides.push(Slide {
            number: slide_num,
            title: "Thank You & Questions".to_string(),
            slide_type: "Closing".to_string(),
            duration_secs: 30,
            key_points: vec![
                "Contact: [email]".to_string(),
                "More info: [website/link]".to_string(),
                "Questions welcome!".to_string(),
            ],
            visual_suggestion: "Contact information with QR code or department logo".to_string(),
            notes: "End confidently. Invite questions warmly. Have backup slides ready for anticipated Q&A.".to_string(),
        });

        let markdown = build_slide_markdown(topic, talk_type, &slides, include_notes);
        let total_duration_secs: u32 = slides.iter().map(|s| s.duration_secs).sum();
        let total_duration_min = (total_duration_secs as f32 / 60.0).ceil() as usize;

        Ok(serde_json::json!({
            "topic": topic,
            "talk_type": talk_type,
            "slide_count": slides.len(),
            "estimated_duration_min": total_duration_min,
            "focus_areas": focus,
            "markdown": markdown,
        }))
    }
}
