[package]
name = "rairos-db-migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "sqlite"] }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
log = "0.4"
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies]
tokio-test = "0.4"
