"""Live situation report — regenerated from live data on each call."""

from __future__ import annotations

import json
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from llm.insight.tracker import EvolutionTracker


def generate() -> str:
    """Generate a fresh situation report from current system state."""
    tracker = EvolutionTracker()
    caps = tracker._load_capsules()

    lines = []
    def w(s=""):
        lines.append(s)

    w("=" * 60)
    w("RAIROS LIVE SITUATION REPORT")
    w(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    w("=" * 60)
    w()

    # 1. Gene Pool overview
    w("1. GENE POOL OVERVIEW")
    w("-" * 60)
    w(f"Total: {len(caps)} capsules")
    by_type = {}
    for c in caps:
        by_type[c.action_gap_type] = by_type.get(c.action_gap_type, 0) + 1
    w(f"Gap types: {by_type}")
    avg_s = sum(c.outcome_success_score for c in caps) / len(caps) if caps else 0
    w(f"Avg score: {avg_s:.3f}")
    w(f"High credibility: {sum(1 for c in caps if c.credibility_badge == 'high')}")
    w()

    # 2. Geopolitical capsules (cs.GL)
    geo = [c for c in caps if getattr(c, "source_arxiv_category", "") == "cs.GL"]
    w("2. GEOPOLITICAL INTELLIGENCE")
    w("-" * 60)
    for c in sorted(geo, key=lambda x: x.outcome_success_score, reverse=True):
        w(f"  score={c.outcome_success_score:.2f} [{c.credibility_badge.upper()}] {c.action_gap_title[:70]}")
    w()

    # 3. Research capsules
    research = [c for c in caps if getattr(c, "source_arxiv_category", "") != "cs.GL"]
    w("3. RESEARCH KNOWLEDGE (top 10)")
    w("-" * 60)
    for c in sorted(research, key=lambda x: x.outcome_success_score, reverse=True)[:10]:
        w(f"  score={c.outcome_success_score:.2f} [{c.credibility_badge.upper()}] {c.action_gap_title[:65]}")
    w()

    # 4. Discovered patterns
    pfile = Path.home() / ".ai_research_os" / "patterns.json"
    w("4. DISCOVERED PATTERNS")
    w("-" * 60)
    if pfile.exists():
        data = json.loads(pfile.read_text(encoding="utf-8"))
        for p in data.get("correlations", []):
            w(f"  [{p.get('type', '?')}]")
            for k, v in p.items():
                if k not in ("type", "discovered_at") and v is not None:
                    w(f"    {k}: {v}")
            w()
    w()

    # 5. Event signals
    w("5. KEYWORD SIGNALS")
    w("-" * 60)
    for kw in ["oil", "military", "Hormuz", "earthquake", "ceasefire"]:
        matches = []
        for c in caps:
            score = c.trigger_match(kw, c.trigger_gap_type, c.trigger_keywords)
            if score > 0.3:
                matches.append((score, c))
        matches.sort(key=lambda x: x[0], reverse=True)
        if matches:
            w(f"  '{kw}': {len(matches)} matches")
            for score, c in matches[:3]:
                w(f"    {score:.2f} {c.action_gap_title[:60]}")
    w()

    # 6. Stats
    w("6. SYSTEM STATS")
    w("-" * 60)
    w(f"Total CLI commands: 30+")
    w(f"Web UI routes: 90")
    w(f"Data sources: ArXiv + Jin10 MCP + RSS News")
    w(f"Run modes: CLI + Web UI + Docker + Daemon")
    w()

    w("=" * 60)
    w("REPORT AUTO-GENERATED BY RAIROS")
    w("=" * 60)

    return "\n".join(lines)


def save() -> str:
    """Generate and save the report to disk."""
    report = generate()
    path = "SITUATION_REPORT.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(report)
    return path
