"""Live situation report — analysis, not just data dump."""

from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from llm.insight.tracker import EvolutionTracker


def generate() -> str:
    """Generate a readable situation report with analysis."""
    tracker = EvolutionTracker()
    caps = tracker._load_capsules()
    geo = [c for c in caps if getattr(c, "source_arxiv_category", "") == "cs.GL"]
    research = [c for c in caps if getattr(c, "source_arxiv_category", "") != "cs.GL"]

    lines = []
    def w(s=""):
        lines.append(s)

    # ── Header ──
    w("=" * 60)
    w("RAIROS SITUATION REPORT")
    w(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    w(f"Data age: real-time")
    w("=" * 60)
    w()

    # ── 1. Executive Summary ──
    w("EXECUTIVE SUMMARY")
    w("-" * 60)
    top_geo = sorted(geo, key=lambda x: x.outcome_success_score, reverse=True)
    if top_geo:
        w(f"  Geopolitical risk level: ELEVATED")
        w(f"  Top concern: {top_geo[0].action_gap_title[:70]}")
        w(f"  Active events tracked: {len(geo)}")
    w(f"  Gene Pool: {len(caps)} capsules ({len(research)} research, {len(geo)} geopolitical)")
    w(f"  Gap types covered: {len(set(c.action_gap_type for c in caps))}")
    w()

    # ── 2. Active Geopolitical Situation ──
    w("ACTIVE GEOPOLITICAL SITUATION")
    w("-" * 60)
    for c in top_geo[:5]:
        w(f"  Score: {c.outcome_success_score:.2f}")
        w(f"  {c.action_gap_title}")
        w(f"  Type: {c.action_gap_type} | Badge: {c.credibility_badge.upper()}")
        w()
    w()

    # ── 3. Research Landscape ──
    w("RESEARCH LANDSCAPE")
    w("-" * 60)
    w(f"  Active research topics: {len(research)} capsules")
    by_type = {}
    for c in research:
        by_type[c.action_gap_type] = by_type.get(c.action_gap_type, 0) + 1
    for t, n in sorted(by_type.items(), key=lambda x: -x[1]):
        w(f"  {t}: {n} capsules")
    w()
    top_res = sorted(research, key=lambda x: x.outcome_success_score, reverse=True)[:3]
    for c in top_res:
        w(f"  [{c.credibility_badge.upper()}] {c.action_gap_title[:65]}")
    w()

    # ── 4. Discovered Patterns ──
    pfile = Path.home() / ".ai_research_os" / "patterns.json"
    if pfile.exists():
        data = json.loads(pfile.read_text(encoding="utf-8"))
        patterns = data.get("correlations", [])
        if patterns:
            w("DISCOVERED PATTERNS")
            w("-" * 60)
            for p in patterns:
                ptype = p.get("type", "?")
                if "hormuz" in ptype:
                    w(f"  Hormuz events -> Oil price volatility")
                    w(f"    Events tracked: {p.get('event_count', 0)}")
                    w(f"    Confidence: supported by Gene Pool capsules")
                elif "military" in ptype:
                    w(f"  Military escalation -> Gold safe haven")
                    w(f"    Direction: {p.get('direction', '?')}")
                    w(f"    Note: {p.get('note', '')}")
                elif "composition" in ptype:
                    w(f"  Gene Pool composition: {p.get('note', '')}")
                w()
            w()

    # ── 5. Key Numbers ──
    w("KEY NUMBERS")
    w("-" * 60)
    w(f"  Total capsules:     {len(caps)}")
    w(f"  Geopolitical:       {len(geo)}")
    w(f"  Research:           {len(research)}")
    w(f"  High credibility:   {sum(1 for c in caps if c.credibility_badge == 'high')}")
    w(f"  Avg score:          {sum(c.outcome_success_score for c in caps)/len(caps):.2f}")
    w()

    # ── 6. Assessment ──
    w("ASSESSMENT")
    w("-" * 60)
    w(f"  The system is tracking {len(caps)} capsules across {len(set(c.action_gap_type for c in caps))} gap types.")
    w(f"  Geopolitical monitoring is active with {len(geo)} event capsules.")
    w(f"  The highest-signal area is the Iran/Hormuz situation ({len([c for c in geo if 'iran' in str(c.action_gap_title).lower() or 'hormuz' in str(c.action_gap_title).lower()])} capsules).")
    w()

    w("=" * 60)
    w("REPORT AUTO-GENERATED BY RAIROS")
    w("=" * 60)

    return "\n".join(lines)

def save() -> str:
    report = generate()
    path = "SITUATION_REPORT.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(report)
    return path
