[package]
name = "rairos-db-py"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "rairos_db_py"
crate-type = ["cdylib"]

[dependencies]
rairos-db = { path = "../rairos-db" }
pyo3 = { version = "0.22", features = ["extension-module"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
