[package]
name = "rairos-db-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "rairos_db_py"
crate-type = ["cdylib"]

[dependencies]
rairos-core = { path = "../rairos-core" }
rusqlite = { version = "0.39", features = ["bundled"] }
pyo3 = { version = "0.24.1", features = ["extension-module"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
