[package]
name = "rairos-evolution-report"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono.workspace = true
dirs.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }
regex.workspace = true
lazy_static.workspace = true
rairos-evolution = { path = "../rairos-evolution" }

[dev-dependencies]
tempfile.workspace = true