[package]
name = "rairos-questions"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json.workspace = true
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
dirs.workspace = true
anyhow.workspace = true
log = "0.4"

[dev-dependencies]
tempfile.workspace = true
