[package]
name = "rairos-questions"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4"] }
dirs.workspace = true
anyhow.workspace = true
log = "0.4"

[dev-dependencies]
tempfile.workspace = true
