[package]
name = "rairos-gene-pool-io"
version = "0.1.0"
edition = "2021"

[dependencies]
rairos-core = { path = "../rairos-core" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
dirs.workspace = true
chrono = { workspace = true, features = ["serde"] }

[dev-dependencies]
tempfile.workspace = true
