[package]
name = "rairos-observability"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono = { workspace = true, features = ["serde"] }
rand.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dirs.workspace = true
tracing-appender.workspace = true

[features]
default = []
otlp = ["dep:opentelemetry", "dep:opentelemetry-otlp", "dep:opentelemetry_sdk", "dep:tracing-opentelemetry"]

[dependencies.opentelemetry]
workspace = true
optional = true

[dependencies.opentelemetry-otlp]
workspace = true
optional = true

[dependencies.opentelemetry_sdk]
workspace = true
optional = true

[dependencies.tracing-opentelemetry]
workspace = true
optional = true

